# -*- coding: utf-8 -*-
"""exammod2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M3LOX8W39zqrMOmMCETWy1xdp1k1uXuT
"""

'''Q.1) Convert given hrs & mins in second'''
hrs=input("enter the hour")
mins = input("enter the mins")

seconds = int(hrs)* 360 + int(mins)*60
print("seconds=",seconds)

'''Q.2) Write code to find the average of ‘n’
numbers entered by the user to function avg ( ).
Ex: avg (10, 20, 30, 40) => average is: 70
avg (5, 10, 15) => average is: 10'''



def avg(a):
    print(a)
    print(sum(a)/len(a))

element = input("how many element you want")
element = int(element)
a=[ ]
for i in range(0,element):
    num= int(input("enter the number"))
    a.append(num)

avg(a)

# Q 3create math class


class Math:
    def __init__(self,a,b):
        self.a = a
        self.b=b
    def add(self):
        print(self.a + self.b)
    def div(self):
        print(self.a / self.b)
    def sub(self):
        print(self.a - self.b)
    def mul(self):
        print(self.a * self.b)


cal = Math(2,4)
cal.add()
cal.div()
cal.sub()
cal.mul()

# Q 4 print

a = 0
for i in range(1,6):
    for j in range(i):

        a=a+1
        
        print(a%2,end="")
    print()

# Q 5



a = int(input("enter the 1st number "))
b = int(input("enter the 2nd number"))
oper = input("enter the operation like addition for (Add) , subtraction for (sub), multiplication for (mul), division for (div) (exit)")

def calci(a,b,oper):
    if "add" == oper.lower():
        print(a+b)
    if "sub" == oper.lower():
        print(a-b)
    if "div" == oper.lower():
        print(a/b)
    if "mul" == oper.lower():
        print(a*b)
    if "exit" == oper.lower():
        print("exit")
calci(a,b,oper)

# Q6
money = input("enter the ruppes and paisa")

a = money.split(".")
print("Rupees:" ,a[0],"Paise:", a[1])

